# This is a basic workflow to help you get started with Actions

name: ZIP the source and upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    name: Build the stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Upload
        env: # Or as an environment variable
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        run: |
          chmod +x $GITHUB_WORKSPACE/action.sh
          $GITHUB_WORKSPACE/action.sh
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
          environment: azurecloud
          audience: https://github.com/chgeuer
      - name: 'CLI'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.37.0
          inlineScript: |
            az storage blob upload --auth-mode login --account-name isvreleases --container-name backendrelease --overwrite --file src.zip --name "test-${GITHUB_SHA}.zip" 
